### ISSUE TITLE
[Question] Hi, Curious 'bout how do you make this preview image

### ISSUE THREAD

**Issue by Moyf** [mProjectsCode/obsidian-focus-theme#5]
Sorry to put this question as an issue, I'm not sure where else should I ask question 😖

But I'm really curious about the image :
![image](https://github.com/mProjectsCode/obsidian-focus-theme/assets/4013062/8106e1c7-4209-4079-a963-067c109410af)
(Hide all the text content of OB)

I've searched like "privacy mode" but only found a plugin called PrivacyGlasses.
Would you mind please share the way how you made it ?

**Comment by mProjectsCode** [comment]
I used [this](https://www.moritzjung.dev/obsidian-stats/plugins/obsidian-theme-design-utilities/) plugin. It has a command named `Toggle Garbled Text`.

**Comment by Moyf** [comment]
Roger that, thank you!

( BTW I viewed your web site, the artworks - as well as your Avatar - are so cool!! And just realized that JS Engine and Metabind are both your work, they're both very useful plugins, thanks for developing ! <3 )

**Comment by mProjectsCode** [comment]
thanks :)
